### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by tusbar** [edx/xblock-utils#28]
I am wondering why this repository is licensed under AGPLv3 while XBlock is licensed under Apache 2.

Is there any specific reason?

It’s caused an issue on the xblock-officemix repo [here](https://github.com/OfficeDev/xblock-officemix/pull/6#discussion_r41453939).

cc @antoviaque @sarina @mollydb

**Comment by antoviaque** [comment]
@tusbar This is because the code was extracted from https://github.com/open-craft/problem-builder which is AGPLv3 licensed, so it needed to preserve the license.

And, not to start a troll war as this is more of a personal view, but for me that's actually a good thing - when the code we produce is reused or built upon, I like to know that the code is going to be open, and remain so.

**Comment by tusbar** [comment]
@antoviaque I understand that. Unfortunately, I will not be able to use xblock-utils for github.com/officedev/xblock-officemix.

**Comment by sarina** [comment]
@nedbat fyi

**Comment by tusbar** [comment]
@antoviaque as we discussed, this won’t change, so I’m closing this.
